services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vard-mini-task
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vard-mini-task-backend
    ports:
      - "5129:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=vard-mini-task;Database=VardSecDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
      - Jwt__Key=${Jwt__Key}
      - Jwt__Issuer=VardSecApp
      - Jwt__Audience=VardSecUsers
    depends_on:
      - mssql
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vard-mini-task-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  mssql_data:
