services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vardsec-mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD:-YOUR_STRONG_PASSWORD_HERE} # Set via .env or CLI
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
